#
#  Makefile for Examples, Chapter 5
#

all: pointer binary twodim 

pointer: pointer.c
	gcc -o pointer pointer.c

binary: binary.c
	gcc -o binary binary.c

twodim: twodim.c
	gcc -o twodim twodim.c

clean: 
	rm pointer binary twodim 


