#
#  Makefile for Solutions, Chapter 6
#

all: 6-1 6-2 6-3 6-4 6-5 6-6

6-1: 6-1.c
	gcc -o 6-1 6-1.c

6-2: 6-2.c
	gcc -o 6-2 6-2.c

6-3: 6-3.c
	gcc -o 6-3 6-3.c

6-4: 6-4.c
	gcc -o 6-4 6-4.c

6-5: 6-5.c
	gcc -o 6-5 6-5.c
	
6-6: 6-6.c
	gcc -o 6-6 6-6.c	
clean: 
	rm 6-1 6-2 6-3 6-4 6-5 6-6
