all: C-1 C-2 C-3 C-4

C-1: C-1.c
	gcc -o C-1 C-1.c

C-2: C-2.c
	gcc -o C-2 C-2.c

C-3: C-3.c
	gcc -o C-3 C-3.c

C-4: C-4.c
	gcc -o C-4 C-4.c

C-5: C-5.c
	gcc -o C-5 C-5.c

clean: 
	rm C-1 C-2 C-3 C-4