all: checkers cshift radixsort

checkers: checkers.c
	gcc -o checkers checkers.c

cshift: cshift.c
	gcc -o cshift cshift.c

radixsort: radixsort.c
	gcc -o radixsort radixsort.c

clean: 
	rm checkers cshift radixsort